#!/usr/bin/env bash
# Generate /etc/khepree/.env.production with random secrets + values from .env.example.
# Run on VPS via deploy-local-to-vps.ps1 or manually:
#   sudo ./bootstrap-vps-env.sh /etc/khepree/.env.production
#
# Does NOT print secret values. Overwrites target file.

set -euo pipefail

TARGET="${1:-/etc/khepree/.env.production}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${SCRIPT_DIR}"
if [[ -f "${SCRIPT_DIR}/../../.env.production.example" ]]; then
  REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
fi
EXAMPLE="${REPO_ROOT}/.env.production.example"
LOCAL_EXAMPLE="${REPO_ROOT}/.env.example"

rand_b64() {
  openssl rand -base64 32 | tr -d '\n'
}

rand_urlsafe() {
  openssl rand -hex 24
}

license_keys() {
  node -e "
const { generateKeyPairSync } = require('crypto');
const k = generateKeyPairSync('ed25519');
process.stdout.write(k.privateKey.export({ type: 'pkcs8', format: 'der' }).toString('base64'));
process.stdout.write('\n');
process.stdout.write(k.publicKey.export({ type: 'spki', format: 'der' }).toString('base64'));
"
}

read_example_val() {
  local key="$1"
  local file="$2"
  grep -E "^${key}=" "$file" 2>/dev/null | head -1 | cut -d= -f2- || true
}

if [[ ! -f "${EXAMPLE}" ]]; then
  echo "error: missing ${EXAMPLE}" >&2
  exit 1
fi

PG_USER="khepree_$(openssl rand -hex 4)"
PG_PASS="$(rand_urlsafe)"
PG_DB="khepree"
REDIS_PASS="$(rand_urlsafe)"
AUTH_SECRET="$(rand_b64)"
OUTBOX_SECRET="$(rand_b64)"

mapfile -t LICENSE < <(license_keys)
LICENSE_PRIVATE="${LICENSE[0]}"
LICENSE_PUBLIC="${LICENSE[1]}"

S3_ENDPOINT="$(read_example_val S3_ENDPOINT "${LOCAL_EXAMPLE}")"
S3_REGION="$(read_example_val S3_REGION "${LOCAL_EXAMPLE}")"
S3_ACCESS_KEY_ID="$(read_example_val S3_ACCESS_KEY_ID "${LOCAL_EXAMPLE}")"
S3_SECRET_ACCESS_KEY="$(read_example_val S3_SECRET_ACCESS_KEY "${LOCAL_EXAMPLE}")"
S3_FORCE_PATH_STYLE="$(read_example_val S3_FORCE_PATH_STYLE "${LOCAL_EXAMPLE}")"
S3_FORCE_PATH_STYLE="${S3_FORCE_PATH_STYLE:-true}"

CHAPMEE_ENV="/opt/chapmee/app/.env.production"
SMTP_HOST="172.18.0.1"
SMTP_PORT="25"
SMTP_USER=""
SMTP_PASS=""
SMTP_SECURE="false"
if [[ -f "${CHAPMEE_ENV}" ]]; then
  SMTP_HOST="$(grep -E '^SMTP_HOST=' "${CHAPMEE_ENV}" | cut -d= -f2- || echo "${SMTP_HOST}")"
  SMTP_PORT="$(grep -E '^SMTP_PORT=' "${CHAPMEE_ENV}" | cut -d= -f2- || echo "${SMTP_PORT}")"
  SMTP_USER="$(grep -E '^SMTP_USER=' "${CHAPMEE_ENV}" | cut -d= -f2- || true)"
  SMTP_PASS="$(grep -E '^SMTP_PASS=' "${CHAPMEE_ENV}" | cut -d= -f2- || true)"
  SMTP_SECURE="$(grep -E '^SMTP_SECURE=' "${CHAPMEE_ENV}" | cut -d= -f2- || echo false)"
fi

# SePay VietQR placeholders — replace with real bank account from SePay dashboard.
SEPAY_BANK_CODE="MBBank"
SEPAY_BANK_ACCOUNT_NUMBER="0123456789"
SEPAY_BANK_ACCOUNT_NAME="KHEPREE"
SEPAY_WEBHOOK_SECRET="sandbox-webhook-secret-minimum-length"

umask 077
cat > "${TARGET}" <<EOF
# Generated by bootstrap-vps-env.sh — do not commit
POSTGRES_USER=${PG_USER}
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_DB=${PG_DB}

REDIS_PASSWORD=${REDIS_PASS}

WEB_URL=https://khepree.com
APP_URL=https://khepree.com
ACCOUNT_URL=https://account.khepree.com
ADMIN_URL=https://admin.khepree.com
PARTNER_URL=https://partner.khepree.com
API_URL=https://api.khepree.com

NEXT_PUBLIC_WEB_URL=https://khepree.com
NEXT_PUBLIC_ACCOUNT_URL=https://account.khepree.com
NEXT_PUBLIC_ADMIN_URL=https://admin.khepree.com
NEXT_PUBLIC_PARTNER_URL=https://partner.khepree.com

BETTER_AUTH_SECRET=${AUTH_SECRET}
BETTER_AUTH_URL=https://account.khepree.com
TRUSTED_PROXY=none

STORAGE_PROVIDER=s3
S3_ENDPOINT=${S3_ENDPOINT:-https://s3.vn-hcm-1.vietnix.cloud}
S3_REGION=${S3_REGION:-vn-hcm-1}
S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
S3_BUCKET_PUBLIC=khepree-public
S3_BUCKET_PRIVATE=khepree-private
S3_PUBLIC_BASE_URL=https://cdn.khepree.com
S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE}
S3_PUBLIC_ACCESS_MODE=acl

LICENSE_SIGNING_PRIVATE_KEY=${LICENSE_PRIVATE}
LICENSE_SIGNING_PUBLIC_KEY=${LICENSE_PUBLIC}

EMAIL_PROVIDER=smtp
MAIL_FROM=Khepree <no-reply@khepree.com>
MAIL_REPLY_TO=support@khepree.com
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
SMTP_SECURE=${SMTP_SECURE}

PAYMENT_PROVIDER=sepay
SEPAY_ENV=production
SEPAY_BANK_CODE=${SEPAY_BANK_CODE}
SEPAY_BANK_ACCOUNT_NUMBER=${SEPAY_BANK_ACCOUNT_NUMBER}
SEPAY_BANK_ACCOUNT_NAME=${SEPAY_BANK_ACCOUNT_NAME}
SEPAY_WEBHOOK_SECRET=${SEPAY_WEBHOOK_SECRET}

OUTBOX_WORKER_SECRET=${OUTBOX_SECRET}
OUTBOX_POLL_INTERVAL_MS=5000
OUTBOX_BATCH_SIZE=20
OUTBOX_LOCK_TIMEOUT_MS=300000
OUTBOX_MAX_ATTEMPTS=12

DATABASE_POOL_MAX=10
DATABASE_IDLE_TIMEOUT=20
DATABASE_CONNECT_TIMEOUT=10

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

KHEPREE_WEB_IMAGE=khepree-web:production
KHEPREE_ACCOUNT_IMAGE=khepree-account:production
KHEPREE_ADMIN_IMAGE=khepree-admin:production
KHEPREE_PARTNER_IMAGE=khepree-partner:production
KHEPREE_API_IMAGE=khepree-api:production
KHEPREE_MIGRATE_IMAGE=khepree-migrate:production
KHEPREE_WORKER_IMAGE=khepree-outbox-worker:production
EOF

chmod 640 "${TARGET}"
echo "Wrote ${TARGET} ($(wc -l < "${TARGET}") lines)"
